name: Trigger GH Pages Build Workflow

on:
  push:
    branches: ["main"]

jobs:
  trigger:
    name: Send Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Send Post
        run: |

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/LambertSchulze/memex/dispatches \
            -d "{\"event_type\": \"trigger-workflow\"}"
